<a href="https://colab.research.google.com/github/vaasanthini/MLBASICS/blob/main/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perform arithmetic operations on NumPy arrays


In [32]:
import numpy as np
a = np.array([1,2,3]) #array a
b =np.array([1]) #array b
c = a + b #addition
d = a - b #subtraction
e = a * b #multiplication
f = a / b
print(c,d,e,f) #print result

[2 3 4] [0 1 2] [1 2 3] [1. 2. 3.]


# Write a script to compute the mean and standard deviation of a NumPy array

In [6]:
import numpy as np
a = np.array([1,2,3,4]) #create array a
mean_a = np.mean(a) #find mean
print(f"the mean is : {mean_a}") #print mean
std_a = np.std(a) #find standard deviation
print(f"the standard deviation is : {std_a}") #print standard deviation


the mean is : 2.5
the standard deviation is : 1.118033988749895


# Create a NumPy array of integers from 10 to 50 with a step size of 5

In [8]:
import numpy as np
array = np.arange(10,51,5)
print(f"the array is : {array}") #arange(start_value, last_value + 1, size)

the array is : [10 15 20 25 30 35 40 45 50]


# Reshape the array into a 2x4 matrix.

In [21]:
import numpy as np
array = np.arange(5,21,5) #create the array
reshaped_array = array.reshape(2,2) #reshape teh array
print(f"the original array is : {array}") #print the original array
print(f"the reshaped array is : {reshaped_array}") #print the reshaped array

the original array is : [ 5 10 15 20]
the reshaped array is : [[ 5 10]
 [15 20]]


Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
Extract the sub-matrix containing the last two rows and first two columns.
Replace all elements greater than 4 with 0.

In [22]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) #create the array
submatrix_arr = arr[1:,:2] #find the submatrix
submatrix = submatrix_arr[submatrix_arr > 4] #replace elements greater than 4 by 0
print(f"the submatrix is : {submatrix}") #print the result

the submatrix is : [5 7 8]


# Create two 1D arrays: a = np.array([1, 2, 3]) b = np.array([4, 5, 6]) Perform element-wise addition, multiplication, and division.

> Add blockquote



In [26]:
import numpy as np
a = np.array([1,2,3]) #create array
b = np.array([4,5,6])
addition = a + b #add
multiplication = a*b #subtract
division = a / b #multiply
#print the result
print(f"element wise addition is : {addition}")
print(f"element wise multiplication is : {multiplication}")
print(f"element wise division is : {division}")

element wise addition is : [5 7 9]
element wise multiplication is : [ 4 10 18]
element wise division is : [0.25 0.4  0.5 ]


# Create a random NumPy array of size (4,4). Compute:
# Mean of each column.
# Maximum value of the entire array.
# Sum of all elements.

In [27]:
import numpy as np
random_array = np.random.rand(4,4) #create a random arr
mean_column =np.mean(random_array,axis=0) #to find column wise mean
max_val = np.max(random_array) #max value of the result array
sum_array = np.sum(random_array) #sum of all elemennts
print(f"mean of each column are : {mean_column}")
print(f"maximum value of the entire array is : {max_val}")
print(f"sum of all elements in the array is : {sum_array}")

mean of each column are : [0.6143209  0.77768804 0.55517818 0.34310345]
maximum value of the entire array is : 0.9558367410970505
sum of all elements in the array is : 9.161162305154004


# Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2

In [28]:
import numpy as np
array = np.array([1,2,3,4]) #create a array
result = (array + 10) * 2
print(f"the resultant array is : {result}") #print the result

the resultant array is : [22 24 26 28]


# Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100. Perform the following:
# Extract the second "layer" (i.e., the second 2D array) in the first dimension.
# Extract the first two rows and the last three columns from each "layer."
## Replace all elements divisible by 3 with -1.

In [30]:
import numpy as np
arr = np.random.randint(1, 101, size=(3, 4, 5)) #create an array
second_layer = arr[1, :, :]
print("Second layer:\n", second_layer) #2d array
sub_array = arr[:, :2, -3:]
print("\nSub-array:\n", sub_array) #first 2 rows and last 3 columns
arr[arr % 3 == 0] = -1 #if divisible by 3 then replace by -1
print("\nModified array:\n", arr) #print the resultant array

Second layer:
 [[72 30 61  3 17]
 [85 19 36 43 40]
 [44 55 53 29 47]
 [80 27 30 40 83]]

Sub-array:
 [[[60 63 85]
  [71 77 35]]

 [[61  3 17]
  [36 43 40]]

 [[43 16 12]
  [65  9 28]]]

Modified array:
 [[[ 22  -1  -1  -1  85]
  [ 10  -1  71  77  35]
  [ -1  97  35  82  -1]
  [ 91  26  38  26  -1]]

 [[ -1  -1  61  -1  17]
  [ 85  19  -1  43  40]
  [ 44  55  53  29  47]
  [ 80  -1  -1  40  83]]

 [[ 44   8  43  16  -1]
  [ 46  -1  65  -1  28]
  [ 59   1 100  34  10]
  [ -1  38 100  97  61]]]


# Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20. Perform the following:
# Subtract the mean of each row from its respective elements (row-wise normalization).
# Create a new array by squaring all the elements in arr.
# Find the indices of the top 3 maximum values in the entire array.

In [31]:

import numpy as np
arr = np.random.randint(1, 21, size=(3, 3)) #create an array
row_means = np.mean(arr, axis=1, keepdims=True) #find mean
normalized_arr = arr - row_means #element - mean
squared_arr = np.square(arr) # squared array
indices = np.argpartition(arr.flatten(), -3)[-3:] # indices of the top3 max values
#print the result
print("Original array:\n", arr)
print("\nRow wise normalized array:\n", normalized_arr)
print("\nSquared array:\n", squared_arr)
print("\nIndices of top 3 maximum values in the entire array:", indices)

Original array:
 [[ 8 16  3]
 [20 18  6]
 [ 4  1 20]]

Row wise normalized array:
 [[-1.          7.         -6.        ]
 [ 5.33333333  3.33333333 -8.66666667]
 [-4.33333333 -7.33333333 11.66666667]]

Squared array:
 [[ 64 256   9]
 [400 324  36]
 [ 16   1 400]]

Indices of top 3 maximum values in the entire array: [4 3 8]
